From netsoft2020tutorial4demo2exp2

COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc.conf
COPY amf.conf /free5gc/install/etc/free5gc/freeDiameter/amf.conf

EXPOSE 36412

CMD /free5gc/free5gc-amfd
